//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InputForm.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gbhg.gov.cn/GBCustoms_EHS_WebService", ConfigurationName="ServiceReference1.GBCustoms_EHS_WebServiceSoap")]
    public interface GBCustoms_EHS_WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gbhg.gov.cn/GBCustoms_EHS_WebService/GBCustoms_ServiceEntrance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        InputForm.ServiceReference1.GBCustoms_ServiceEntranceResponse GBCustoms_ServiceEntrance(InputForm.ServiceReference1.GBCustoms_ServiceEntranceRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://gbhg.gov.cn/GBCustoms_EHS_WebService/GBCustoms_ServiceEntrance", ReplyAction="*")]
        System.Threading.Tasks.Task<InputForm.ServiceReference1.GBCustoms_ServiceEntranceResponse> GBCustoms_ServiceEntranceAsync(InputForm.ServiceReference1.GBCustoms_ServiceEntranceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GBCustoms_ServiceEntrance", WrapperNamespace="http://gbhg.gov.cn/GBCustoms_EHS_WebService", IsWrapped=true)]
    public partial class GBCustoms_ServiceEntranceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gbhg.gov.cn/GBCustoms_EHS_WebService", Order=0)]
        public string strVOYAGE_NO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gbhg.gov.cn/GBCustoms_EHS_WebService", Order=1)]
        public string strUserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gbhg.gov.cn/GBCustoms_EHS_WebService", Order=2)]
        public string strUserPWD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gbhg.gov.cn/GBCustoms_EHS_WebService", Order=3)]
        public string strVisitorNO;
        
        public GBCustoms_ServiceEntranceRequest() {
        }
        
        public GBCustoms_ServiceEntranceRequest(string strVOYAGE_NO, string strUserID, string strUserPWD, string strVisitorNO) {
            this.strVOYAGE_NO = strVOYAGE_NO;
            this.strUserID = strUserID;
            this.strUserPWD = strUserPWD;
            this.strVisitorNO = strVisitorNO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GBCustoms_ServiceEntranceResponse", WrapperNamespace="http://gbhg.gov.cn/GBCustoms_EHS_WebService", IsWrapped=true)]
    public partial class GBCustoms_ServiceEntranceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gbhg.gov.cn/GBCustoms_EHS_WebService", Order=0)]
        public System.Data.DataSet GBCustoms_ServiceEntranceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gbhg.gov.cn/GBCustoms_EHS_WebService", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] outMessage;
        
        public GBCustoms_ServiceEntranceResponse() {
        }
        
        public GBCustoms_ServiceEntranceResponse(System.Data.DataSet GBCustoms_ServiceEntranceResult, string[][] outMessage) {
            this.GBCustoms_ServiceEntranceResult = GBCustoms_ServiceEntranceResult;
            this.outMessage = outMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GBCustoms_EHS_WebServiceSoapChannel : InputForm.ServiceReference1.GBCustoms_EHS_WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBCustoms_EHS_WebServiceSoapClient : System.ServiceModel.ClientBase<InputForm.ServiceReference1.GBCustoms_EHS_WebServiceSoap>, InputForm.ServiceReference1.GBCustoms_EHS_WebServiceSoap {
        
        public GBCustoms_EHS_WebServiceSoapClient() {
        }
        
        public GBCustoms_EHS_WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBCustoms_EHS_WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBCustoms_EHS_WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBCustoms_EHS_WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InputForm.ServiceReference1.GBCustoms_ServiceEntranceResponse InputForm.ServiceReference1.GBCustoms_EHS_WebServiceSoap.GBCustoms_ServiceEntrance(InputForm.ServiceReference1.GBCustoms_ServiceEntranceRequest request) {
            return base.Channel.GBCustoms_ServiceEntrance(request);
        }
        
        public System.Data.DataSet GBCustoms_ServiceEntrance(string strVOYAGE_NO, string strUserID, string strUserPWD, string strVisitorNO, out string[][] outMessage) {
            InputForm.ServiceReference1.GBCustoms_ServiceEntranceRequest inValue = new InputForm.ServiceReference1.GBCustoms_ServiceEntranceRequest();
            inValue.strVOYAGE_NO = strVOYAGE_NO;
            inValue.strUserID = strUserID;
            inValue.strUserPWD = strUserPWD;
            inValue.strVisitorNO = strVisitorNO;
            InputForm.ServiceReference1.GBCustoms_ServiceEntranceResponse retVal = ((InputForm.ServiceReference1.GBCustoms_EHS_WebServiceSoap)(this)).GBCustoms_ServiceEntrance(inValue);
            outMessage = retVal.outMessage;
            return retVal.GBCustoms_ServiceEntranceResult;
        }
        
        public System.Threading.Tasks.Task<InputForm.ServiceReference1.GBCustoms_ServiceEntranceResponse> GBCustoms_ServiceEntranceAsync(InputForm.ServiceReference1.GBCustoms_ServiceEntranceRequest request) {
            return base.Channel.GBCustoms_ServiceEntranceAsync(request);
        }
    }
}
